runtime: python312

handlers:
# Client files.
- url: /editor
  static_dir: editor
  secure: always

- url: /docs
  static_dir: docs
  secure: always

- url: /third-party
  static_dir: third-party
  secure: always

# Dynamic content.
- url: /.*
  script: auto
  secure: always
