#!/bin/bash

# Script to deploy on GAE.

APP=./app.yaml
if ! [ -f $APP ] ; then
   echo $APP not found 1>&2
   exit 1
fi

PROJECT=glockenspiel
VERSION=live

echo 'Beginning deployment...'
gcloud app deploy --project $PROJECT --version $VERSION --promote
echo 'Deployment finished.'
